global:
    api-listen-addr: :5183
    timeout: 10s
    memo: Yei Finance
    light-cache-size: 20
    log-level: info
    ics20-memo-limit: 0
    max-receiver-size: 150
chains:
    noble:
        type: cosmos
        value:
            key-directory: /Users/benjamin/.relayer/keys/noble-1
            key: yei
            chain-id: noble-1
            rpc-addr: https://rpc.lavenderfive.com:443/noble
            account-prefix: noble
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01ustake
            min-gas-amount: 0
            max-gas-amount: 0
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
    sei:
        type: cosmos
        value:
            key-directory: /Users/benjamin/.relayer/keys/pacific-1
            key: yei
            chain-id: pacific-1
            rpc-addr: https://rpc.sei-apis.com:443/?x-apikey=d0227c6f
            account-prefix: sei
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01usei
            min-gas-amount: 0
            max-gas-amount: 0
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
paths:
    noble-sei:
        src:
            chain-id: noble-1
            client-id: 07-tendermint-45
            connection-id: connection-61
        dst:
            chain-id: pacific-1
            client-id: 07-tendermint-45
            connection-id: connection-77
        src-channel-filter:
            rule: ""
            channel-list: []
    yei_finance:
        src:
            chain-id: noble-1
        dst:
            chain-id: pacific-1
        src-channel-filter:
            rule: ""
            channel-list: []
